spring:
  profiles:
    active: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newsapp
    username: root
    password: password
  session:
    store:
      type: redis
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

#---
#spring:
#  profiles:
#    active: production
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql-master:3306/newsapp
#    username: root
#    password: password
#  session:
#    store:
#      type: redis
#  redis:
#    host: redis
#    port: 6379
#  servlet:
#    multipart:
#      max-file-size: 30MB
#      max-request-size: 30MB

##
##logging.level.org.springframework: debug

