version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    working_directory: /NewsApp
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: GCP Authenticate
#            echo -n $GCLOUD_SERVICE_KEY | base64 --decode > gcloud-service-key.json
#            gcloud auth activate-service-account  --key-file gcloud-service-key.json
#            gcloud --quiet config set project "$GOOGLE_PROJECT_ID"
#      - run:
#          name: Build image
#          command:
#              docker build -t asia.gcr.io/newsapp-273606/newsappjdk:$CIRCLE_SHA1 -f /NewsApp/docker/jdk/Dockerfile .
#      - run:
#          name: push image
#          command: |
#            gcloud docker -- push asia.gcr.io/newsapp-273606/newsappjdk:$CIRCLE_SHA1
#      - run:
#          name: deploy
#          command: |
#            kubectl set image deployment/newsapp-api.yaml jdk=asia.gcr.io/newsapp-273606/newsappjdk:latest:${CIRCLE_SHA1}

#workflows :
#  version: 2
#  deploy_production:
#    jobs:
#      - deploy:
#          filters:
#            branches:
#              only:
#                - master




