apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
   - name: http
     port: 80
     targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: asia.gcr.io/newsapp-273606/newsappnginx@sha256:0e23322e7b9e910f4e68ad7cbee6c9905bb47ca6324eadc4e93669b6c55d3cab
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: WORKER_PROCESSES
            value: "2"
          - name: WORKER_CONNECT
            value: "1024"
          - name: LOGS_STDOUT
            value: "true"
          - name: BACKEND_HOST
            value: "newsapp:8080"
          - name: SERVER_NAME
            value: "nginx"