apiVersion: v1                # API version
kind: Service                 # Type of the kubernetes resource
metadata:
  name: newsapp               # Name of the kubernetes resource
  labels:                     # Labels that will be applied to this resource
    app: newsapp
spec:
  selector:
    app: newsapp               # The service exposes Pods with label `app=polling-app-server`
  ports:                      # Forward incoming connections on port 8080 to the target port 8080
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsapp
  labels:
    app: newsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: newsapp
  template:
    metadata:
      labels:
        app: newsapp
    spec:
      containers:
        - name: newsapp
          image: asia.gcr.io/newsapp-273606/newsappjdk@sha256:638eff85373b92245398dd1cf63a0b3ea44b39bd450770093e7b77dd9b7bb9ff
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_URL
              value: "jdbc:mysql://mysql-master:3306/newsapp"